[package]
name = "stsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [build-dependencies] 
# lalrpop = "0.19.7"

[dependencies]
ctrlc = "3.2.3"
rustyline = "10.0.0"
# lalrpop-util = "0.19.7"
# regex = "1"
